version: "3.7"
services:

  ##############
  ## Crawlers ##
  ##############

  c1:
    image: dgoldstein1/crawler:0.2.5
    depends_on:
      - kv
      - graph
    environment:
      - GRAPH_DB_ENDPOINT=http://graph:5000
      - TWO_WAY_KV_ENDPOINT=http://kv:5001
      - STARTING_ENDPOINT=https://en.wikipedia.org/wiki/Tongil_Industries_Company
      - MAX_APPROX_NODES=10000
      - COMMAND=wikipedia
      - METRICS_PORT=8001

  c2:
    image: dgoldstein1/crawler:0.2.5
    depends_on:
      - kv
      - graph
    environment:
      - GRAPH_DB_ENDPOINT=http://graph:5000
      - TWO_WAY_KV_ENDPOINT=http://kv:5001
      - STARTING_ENDPOINT=https://en.wikipedia.org/wiki/Alderon_Iron_Ore_Corp.
      - MAX_APPROX_NODES=10000
      - COMMAND=wikipedia
      - METRICS_PORT=8001

  c3:
    image: dgoldstein1/crawler:0.2.5
    depends_on:
      - kv
      - graph
    environment:
      - GRAPH_DB_ENDPOINT=http://graph:5000
      - TWO_WAY_KV_ENDPOINT=http://kv:5001
      - STARTING_ENDPOINT=https://en.wikipedia.org/wiki/Tigran_Hamasyan
      - MAX_APPROX_NODES=10000
      - COMMAND=wikipedia
      - METRICS_PORT=8001


  ##############
  ## Services ##
  ##############

  kv:
    image: dgoldstein1/twowaykv:0.2.2
    ports:
      - 5001:5001
    depends_on:
      - prom

  graph:
    image: dgoldstein1/biggraph:0.1.1
    ports:
      - 5000:5000
      - 8001:8001
    depends_on:
      - prom


  ################
  ## Monitoring ##
  ################

  prom:
    image: prom/prometheus:v2.11.1
    ports:
      - 9090:9090
    entrypoint: "/bin/prometheus --log.level=debug --config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:6.2.4
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prom
    ports:
    - "3000:3000"
