version: "3.7"
services:

  ##############
  ## Crawlers ##
  ##############

  c1:
    image: dgoldstein1/crawler
    depends_on:
      - kv
      - graph
    environment:
      - GRAPH_DB_ENDPOINT=http://graph:5000
      - TWO_WAY_KV_ENDPOINT=http://kv:5001
      - STARTING_ENDPOINT=https://en.wikipedia.org/wiki/Tongil_Industries_Company
      - MAX_APPROX_NODES=10
      - COMMAND=wikipedia

  c2:
    image: dgoldstein1/crawler
    depends_on:
      - kv
      - graph
    environment:
      - GRAPH_DB_ENDPOINT=http://graph:5000
      - TWO_WAY_KV_ENDPOINT=http://kv:5001
      - STARTING_ENDPOINT=https://en.wikipedia.org/wiki/Alderon_Iron_Ore_Corp.
      - MAX_APPROX_NODES=10
      - COMMAND=wikipedia

  c3:
    image: dgoldstein1/crawler
    depends_on:
      - kv
      - graph
    environment:
      - GRAPH_DB_ENDPOINT=http://graph:5000
      - TWO_WAY_KV_ENDPOINT=http://kv:5001
      - STARTING_ENDPOINT=https://en.wikipedia.org/wiki/Tigran_Hamasyan
      - MAX_APPROX_NODES=10
      - COMMAND=wikipedia


  ##############
  ## Services ##
  ##############

  kv:
    image: dgoldstein1/twowaykv:latest
    ports:
      - 5001:5001

  graph:
    image: dgoldstein1/biggraph:latest
    ports:
      - 5000:5000
      - 8001:8001


  ################
  ## Monitoring ##
  ################

  prom:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    entrypoint: "/bin/prometheus --log.level=debug --config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    # user: "104"
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
      # - ./docker/grafana/data:/var/lib/grafana
    ports:
    - "3000:3000"
