{
 "title": "Crawler Backend",
 "time": { "from": "2019-08-02T13:12:17.019Z", "to": "2019-08-02T16:18:57.019Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_request_count_total[1m])"
    },
    { "expr": "rate(gin_requests_total[1m])" }
   ]
  },
  {
   "title": "Big Graph Successful Response Rate",
   "type": "gauge",
   "description": "Percentage of 2XX Requests",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (http_status) (flask_request_count_total{http_status=~\"2..\"}) / sum by (http_status) (flask_request_count_total)) * 100"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_request_latency_seconds_sum[1m])"
    },
    {
     "expr": "rate(gin_request_duration_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "KV Response Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "(sum by (http_status) (gin_requests_total{code=~\"2..\"}) / sum by (http_status) (gin_requests_total)) * 100"
    }
   ]
  }
 ]
}