apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: edge-ingress
  # annotations:
  #   kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
spec:
  backend:
    serviceName: edge
    servicePort: 80