apiVersion: v1
kind: Service
metadata:
  labels:
    app: crawler
  name: crawler
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8001
  selector:
    app: crawler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
spec:
  selector:
    matchLabels:
      app: crawler
  replicas: 3
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - name: crawler
        image: dgoldstein1/crawler:0.2.6
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
          - name: GRAPH_DB_ENDPOINT
            value: "http://graph:5000"
          - name: TWO_WAY_KV_ENDPOINT
            value: "http://kv:5001"
          - name: MAX_APPROX_NODES
            value: "-1"
          - name: METRICS_PORT
            value: "8001"
          - name: COMMAND
            value: "wikipedia"
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup graph; do echo waiting for graph-service; sleep 7; done;']
        - name: init-mydb
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup kv; do echo waiting for kv-service; sleep 7; done;']
