apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml.k8-config convert
    kompose.service.expose: "true"
    kompose.service.type: nodeport
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: edge
  name: edge
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml.k8-config convert
        kompose.service.expose: "true"
        kompose.service.type: nodeport
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: edge
    spec:
      containers:
      - image: dgoldstein1/crawler-deployment:edge
        name: edge
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
