apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml.k8-config convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml.k8-config convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: grafana
    spec:
      containers:
      - env:
        - name: GF_SERVER_ROOT_URL
          value: '%(protocol)s://%(domain)s:/admin/grafana'
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        image: dgoldstein1/crawler-deployment:grafana
        name: grafana
        resources: {}
      restartPolicy: Always
status: {}
