apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: graph
  name: graph
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: graph
    spec:
      containers:
      - env:
        - name: GRAPH_SAVE_INTERVAL
          value: "60"
        - name: GRAPH_SAVE_PATH
          value: /data/wikipedia_graph.graph
        image: dgoldstein1/biggraph:0.1.5
        name: graph
        ports:
        - containerPort: 5000
        - containerPort: 8001
        resources: {}
      restartPolicy: Always
status: {}
