global:
  scrape_interval: 2s

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets:
          - prom:9090

  - job_name: kv
    static_configs:
      - targets:
          - kv:5001

  - job_name: biggraph
    static_configs:
      - targets:
          - graph:8001
