global:
  scrape_interval: 15s

scrape_configs:

  - job_name: crawler
    scrape_interval: 5s
    static_configs:
      - targets:
          - crawler:5000

  - job_name: kv
    static_configs:
      - targets:
          - kv:5001

  - job_name: biggraph
    static_configs:
      - targets:
          - graph:5000
